### ISSUE TITLE
Impact of log scanning on TeamCity

### ISSUE THREAD

**Issue by big-guy** [etiennestuder/teamcity-build-scan-plugin#11]
Currently, when a completed TC build fails to report a build scan, the plugin falls back to searching the logs of the build for build scans. Builds can report build scans either by using the Gradle runner (which injects an init script) or by applying the [Gradle Build Scan TC plugin](https://github.com/etiennestuder/gradle-build-scan-teamcity-plugin). 

This can cause problems on the TC server in a few different scenarios:
1. The build does not produce a build scan because it doesn't use Gradle or Maven.
1. The build uses Gradle or Maven but does not produce build scans.
1. The build uses Gradle or Maven and produces build scans, but does not use the Gradle runner or `nu.studer.build-scan.teamcity` plugin.
1. The build fails before the step that produces the build scan runs.

It also looks like maybe Maven builds always require scanning?

The fallback behavior can cause a large strain on the TC server if there are enough builds that fall into these scenarios. For organizations that are just trying out build scans, it may not be possible to update all the builds at once or there may be enough builds that would never produce build scans to reduce the impact of the scanning behavior.

As a short term fix, I think it would be reasonable to make this an opt-in option that enables/disables the fallback behavior in an across the board way or disable this fallback behavior completely.  

As a longer term fix, I think it makes sense for the build scan to have [some configuration](https://plugins.jetbrains.com/docs/teamcity/storing-plugin-state-and-settings.html) that can be applied at the Project-level or expose the build scan search as a [build feature](https://plugins.jetbrains.com/docs/teamcity/build-features.html).

**Comment by etiennestuder** [comment]
This was done in [v0.10](https://github.com/etiennestuder/teamcity-build-scan-plugin/releases/tag/v0.10) . See also [here](https://github.com/etiennestuder/teamcity-build-scan-plugin#teamcity-build-runner-requirements).

**Comment by dmitry-treskunov** [comment]
@etiennestuder Hi, could you please clarify how you fixed it? 
By introducing a BUILD_SCAN_LOG_PARSING parameter, right?

**Comment by etiennestuder** [comment]
Yes.

**Comment by dmitry-treskunov** [comment]
Thanks, is it possible to change the default value from true to false? Otherwise, it's not possible to install the plugin to any active server, because it will significantly affect the performance.

**Comment by etiennestuder** [comment]
Set the param on the root config of your server and it will apply to (i.e. inherited by) all build configs.

**Comment by dmitry-treskunov** [comment]
It's a solution you are right, but it breaks TeamCity's builds reuse functionality: all the build chains will have to rebuild their dependencies, which is very undesirable for any active server

**Comment by dmitry-treskunov** [comment]
Basically I see there three options:
* Change the default value to false
* Change the name of the parameter to start with 'teamcity.internal.', ex. 'teamcity.internal.gradleBuildScan.enabled'. Such parameters don't affect builds' reuse
* Implement a [build feature](https://plugins.jetbrains.com/docs/teamcity/build-features.html) that can be added to any build configuration to enable build log scanning. 

What do you think? The third options would be more consistent with other TeamCity functionality, but it requires some effort
