### ISSUE TITLE
Buildscan data cleanup is in sync with the teamcity build     

### ISSUE THREAD

**Issue by jonnybbb** [etiennestuder/teamcity-build-scan-plugin#13]
# Motivation
The buildscan urls are stored in a custom data storage within the teamcity database. The storage format of teamcity lead to an increasing value per build configuration. At the same time the scan data was not cleaned up when the build is deleted from the history during the cleanup procedure. 

# Solution
The custom storage format is replace by the storing the data inside the builds artifacts directory. These files are cleaned up automatically by the teamcity build cleanup procedure and is the [recommened approach by teamcity](https://plugins.jetbrains.com/docs/teamcity/storing-plugin-state-and-settings.html#StoringPluginStateandSettings-Build-levelState)

# Migration
The scan urls are cached and persisted in disk by the cache implementation of the plugin. If a build scan from a older plugin version cannot be resolved by the cache directly the current implementation provides a fallback solution to the old storage implementation. Data that is no longer associated by any 
build should get cleaned up after the database cleanup procedure of teamcity to make space available and improve the performance of old scan lookup as well.

**Comment by etiennestuder** [comment]
The persistence mechanism has been released in v0.12. The clean-up of the legacy persistence will follow in a separate release.
