### ISSUE TITLE
🚫 maven execution output is lost

### ISSUE THREAD

**Issue by seregamorph** [etiennestuder/teamcity-build-scan-plugin#16]
There is a severe problem with the plugin: the Maven execution output is erased.
Please check this screenshot:
![Screen Shot 2020-07-12 at 11 30 29](https://user-images.githubusercontent.com/2844909/87242203-33397080-c433-11ea-9470-40a01ea16d47.png)
There is a single difference between execution 6 and 7: at 6 the plugin is disabled, at 7 the plugin is enabled (and server is restarted; without server restart the issue is not visible).

If you open Overview tab of the execution, there is also difference - tests information is lost:
![Screen Shot 2020-07-12 at 11 33 15](https://user-images.githubusercontent.com/2844909/87242247-93c8ad80-c433-11ea-97a2-ef1317c99529.png)
![Screen Shot 2020-07-12 at 11 33 28](https://user-images.githubusercontent.com/2844909/87242249-962b0780-c433-11ea-90e1-cf604e99aa3f.png)

**Steps to reproduce:**
- create teamcity configuration on maven project (e.g. https://github.com/seregamorph/morejdbc.git  branch master). The build step is `Maven` with targets: `clean verify`
- Disable your plugin
- Restart the TeamCity
- Execute the build - tests execution information is here
- Enable the plugin
- Restart the TeamCity (note: without restart the issue is not visible)
- Execute the build - the test execution information is lost

Hope it is not intended ;)
And JFYI: it was hard to investigate the root cause. Initially I had to downgrade the TeamCity version (painful), because I thought wrong reason.

**Comment by seregamorph** [comment]
![Screen Shot 2020-07-12 at 11 40 54](https://user-images.githubusercontent.com/2844909/87242363-9677d280-c434-11ea-8904-71bdd7256bfa.png)

**Comment by etiennestuder** [comment]
Do you use a vanilla teamcity installation or one where you have installed additional third-party plugins?

**Comment by guylabs** [comment]
@seregamorph could you also send us the logs of the failing run (#7)? Could you also try with the TeamCity build scan plugin version `0.14` and `0.13`? We have found another similar issue where it fails when the TeamCity Artifactory plugin is applied as well. The solution there is to use `0.13` which works. Would be interesting if that works on your side as well.

**Comment by seregamorph** [comment]
TeamCity server version: `2020.1.2` (docker image)

@etiennestuder not a vanilla, but I turned off all plugins except yours and issue is still here.
![Screen Shot 2020-07-13 at 12 19 44](https://user-images.githubusercontent.com/2844909/87288246-c510ae80-c503-11ea-88c6-580cfec03406.png)

@guylabs thanks for advice. I've tried `0.13`, the issue is gone. But `0.14` still has it.
Logs are attached
[Build_with_0.13.log.zip](https://github.com/etiennestuder/teamcity-build-scan-plugin/files/4911709/Build_with_0.13.log.zip)
[Build_with_0.14.log.zip](https://github.com/etiennestuder/teamcity-build-scan-plugin/files/4911710/Build_with_0.14.log.zip)

Guys, please let me know if you cannot reproduce the issue, I'll prepare detailed instruction how I start TeamCity service from scratch (I already have it, just should validate that it is not outdated).

**Comment by guylabs** [comment]
@seregamorph thanks for the details. You can use `0.13` as a short term workaround until that is fixed.

Regarding the logs: The logs for the `0.14` run do not show any `Process exited with code 1` as the screenshot you posted [here](https://github.com/etiennestuder/teamcity-build-scan-plugin/issues/16#issue-655357723). Can you double check that this is the build that failed with version `0.14` applied? Thanks!

**Comment by seregamorph** [comment]
@guylabs good finding. Both logs are for the exact same revision that is success, the difference is only with plugin version. Success maven execution still has the same issue - TeamCity does not show count of executed tests, so this should not make big sense.

**Comment by seregamorph** [comment]
The log of `#7` execution is no more available (this configuration was just created as an ad-hoc to make this report and then deleted, logs are lost). So the logs attached later are not related to the screenshot, but still reflect the case (success execution).

**Comment by guylabs** [comment]
Ok thanks for the update. This information is enough for us to try to reproduce this issue. We'll get back to you once we have an update on this.

**Comment by pbielicki** [comment]
@seregamorph I reproduced this issue on a local TC instance. We're investigating and will let you know as soon as we fix it.

**Comment by etiennestuder** [comment]
The fix will be available in 0.16 later today.
