### ISSUE TITLE
Running full build with JDK 11 creates Java 8 compatible artifacts

### ISSUE THREAD

**Issue by etiennestuder** [etiennestuder/teamcity-build-scan-plugin#172]
Please verify this is the case:
- server compoennt
- agent component
- service message maven extension

**Comment by etiennestuder** [comment]
@clayburn That's evidence enough. Thanks.

**Comment by etiennestuder** [comment]
@clayburn I assume your verification includes the classes of:
- server-side
- agent-side
- service-message-maven-extension (also agent-side, but bundled as an extension jar)

**Comment by clayburn** [comment]
Yes, classes in all 3 jar files
