### ISSUE TITLE
Does not work with jdk version less than 1.8

### ISSUE THREAD

**Issue by madlexa** [etiennestuder/teamcity-build-scan-plugin#20]
A lot of users build their projects with old java.
e.g. [TW-67475](https://youtrack.jetbrains.com/issue/TW-67475)

**Comment by etiennestuder** [comment]
@madlexa I don't fully get it yet. Are you saying some people run TeamCity or TeamCity agents on JDK 1.6? Or are you saying people run TeamCity on newer versions of the JDK but are building projects with JDK 1.6?

**Comment by madlexa** [comment]
@etiennestuder Yes, the second case `People run TeamCity on newer versions of the JDK, but are building their projects with JDK 1.6`

**Comment by etiennestuder** [comment]
Got it. Let me see if I can get GH actions to build the plugin with JDK 1.6.

**Comment by madlexa** [comment]
As a workaround, you can add disable the plugin using parameter `teamcity.internal.<name>.enabled=false`

**Comment by etiennestuder** [comment]
[v0.20](https://github.com/etiennestuder/teamcity-build-scan-plugin/releases/tag/v0.20) has a Gradle agent built with JDK 6 while the server component is built with JDK 8. I will not go any further back in the history of JDKs.
