### ISSUE TITLE
Do not show when "Build scan" tab and info when no build scan available

### ISSUE THREAD

**Issue by burnasheva** [etiennestuder/teamcity-build-scan-plugin#22]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/10289009/95312300-0c9ea080-088f-11eb-9731-5c7db5897e64.png">
Otherwise it is rather intrusive.

**Comment by burnasheva** [comment]
We have a Gradle build step, it's just there is no build scans created.

**Comment by etiennestuder** [comment]
Using the new TC UI, the build scan info does not show up in the `Overview` anymore, and it only shows up in the menu when clicking on the `More v` link. It does not seem to me that it is worthwhile to fix this "issue".

**Comment by dmitry-treskunov** [comment]
Hi,

>the build scan info does not show up in the Overview anymore

This is one is to be fixed, the new UI doesn't support some extension points right now, but we are working on it so it will be possible to include the Build Scan info into the build overview page.

>it only shows up in the menu when clicking on the More v link

This is also to be fixed, new UI will show all the tabs by default (https://youtrack.jetbrains.com/issue/TW-63893)

**Comment by etiennestuder** [comment]
Fixed on master.

**Comment by etiennestuder** [comment]
Released as part of v0.19.
