### ISSUE TITLE
Build Scan tab and scan reference is not shown

### ISSUE THREAD

**Issue by grine4ka** [etiennestuder/teamcity-build-scan-plugin#24]
Hi,

i've installed teamcity-build-scan-plugin v.0.19, but "Build Scan" tab and scan reference isn't shown
<img width="766" alt="Screenshot 2020-10-19 в 13 59 52" src="https://user-images.githubusercontent.com/3784268/96442522-ef18f180-1213-11eb-94a6-eaa213acc8bd.png">

I watched through build logs and found log messages by plugin:
```
##teamcity[nu.studer.teamcity.buildscan.buildScanLifeCycle 'BUILD_STARTED']
##teamcity[nu.studer.teamcity.buildscan.buildScanLifeCycle 'BUILD_SCAN_URL:https://gradle.com/s/eg5erx3kzxp32']
```

I'm using Gradle Runner for the build step and watched that gradle init-scripts are run correctly:
```
gradle 
--init-script \
 /opt/teamcity-agent/plugins/gradle-runner/scripts/init.gradle \
--init-script \
 /opt/teamcity-agent/temp/agentTmp/build-scan-init.gradle \
--no-daemon \
--scan \
detekt \
checkstyle \
testDevDebugUnitTest \
```

Inside android project that I want to build I'm using Gradle Enterprise Plugin version 3.1.1

The only thing I'm thinking about that could break plugin integration - is that I'm using [Docker Wrapper extension](https://www.jetbrains.com/help/teamcity/docker-wrapper.html) for Gradle Runner

TC version: TeamCity Enterprise 2020.1.5 (build 78938)

**Comment by etiennestuder** [comment]
Please try with the latest plugin version:
https://github.com/etiennestuder/teamcity-build-scan-plugin/releases

**Comment by etiennestuder** [comment]
FYI: this is the logic: https://github.com/etiennestuder/teamcity-build-scan-plugin/blob/8204eab65b890fe1043c05327a16a03540d22cfd/src/main/java/nu/studer/teamcity/buildscan/internal/DefaultBuildScanDisplayArbiter.java#L27

**Comment by etiennestuder** [comment]
Could it be that the TC config you have on your branch is not the same you have on master?

**Comment by grine4ka** [comment]
> Could it be that the TC config you have on your branch is not the same that you have on master?

No-no, everything is the same for all branches.

> Please try with the latest plugin version
We'll try to update the plugin version. It's not that easy, cause we reboot teamcity server very rarely, once a week. Anyway, I'll send you feedback.

> FYI: this is the logic
Thanks. I went through that class, everything seems fine for our config. But I'll return to this class later, I guess)

**Comment by etiennestuder** [comment]
@grine4ka Before upgrading, please go to one of your TC builds where you expect to see the build scan link and check if you see this hidden artifact and if so, what does it contain?

<img width="646" alt="Screenshot 2020-10-21 at 15 13 28" src="https://user-images.githubusercontent.com/231070/96724396-1278a380-13b0-11eb-873c-ed799ffb0b77.png">

**Comment by grine4ka** [comment]
> @grine4ka Before upgrading, please go to one of your TC builds where you expect to see the build scan link and check if you see this hidden artifact and if so, what does it contain?
> 
> <img alt="Screenshot 2020-10-21 at 15 13 28" width="646" src="https://user-images.githubusercontent.com/231070/96724396-1278a380-13b0-11eb-873c-ed799ffb0b77.png">

No, there is no build_scans directory
<img width="409" alt="Screenshot 2020-10-21 at 18 22 23" src="https://user-images.githubusercontent.com/3784268/96741417-7019e980-13ca-11eb-8f32-2097a3eb560d.png">

**Comment by etiennestuder** [comment]
This means the message did not make it to the server or the meformat ssage got corrupted somewhere between client and server. If the latter is the case, you should see an error message in the server logs:

https://github.com/etiennestuder/teamcity-build-scan-plugin/blob/a8a007dc4cfd19fb2a3fe0365dec54c96e8d09e4/src/main/java/nu/studer/teamcity/buildscan/internal/BuildScanServiceMessageListener.java#L33-L41

**Comment by etiennestuder** [comment]
@grine4ka I'm going to close this issue due to lack of activity. Should you find some time to investigate further, I'll be happy to assist as much as I can. Also, note that once you have upgraded to v0.21 and restarted the server, future plugin upgrades should be possible without a server restart by simply updating the plugin on the Plugins page in the TeamCity admin section.

**Comment by grine4ka** [comment]
Yep, thanks for help. We are about to update to v0.21. And then I hope I'll have some time to investigate that issue

**Comment by etiennestuder** [comment]
👍
