### ISSUE TITLE
Usage question - use build scan id in following execution step

### ISSUE THREAD

**Issue by dcabasson** [etiennestuder/teamcity-build-scan-plugin#4]
Using this plugin, is it possible to use the build scan id in an upcoming build step?

I am trying to parse some of the content of the build scan following a gradle build, but to do that, I need the build scan id.

Thanks!

**Comment by etiennestuder** [comment]
Unfortunately, not that I can think of.

Maybe TC would allow to store data in scope 'build step' and access it in a later build step. Not sure.

Sorry I do not have anything more specific.

**Comment by dcabasson** [comment]
No worries - I found https://docs.gradle.com/build-scan-plugin/#capturing_the_build_scan_id_or_address since asking the question - I think I am going to write it down in a file and get the next step to read from that file.

**Comment by etiennestuder** [comment]
Nice idea with the file.
