### ISSUE TITLE
Build scan link is not detected in all cases

### ISSUE THREAD

**Issue by facewindu** [etiennestuder/teamcity-build-scan-plugin#5]
See https://github.com/gradle/gradle/issues/5422

**Comment by ldaley** [comment]
@etiennestuder is there a way you can isolate your search to the build `stdout` and ignore `stderr`?

**Comment by etiennestuder** [comment]
I'll take a look.

**Comment by etiennestuder** [comment]
I will close this issue, all references Gradle issues have been resolved. We can reopen the issue if it ocurrs again.
